### ISSUE TITLE
Additional rule Disable Improve Siri & Dictation

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#16]
```
id: sysprefs_improve_siri_dictation_disable
title: "Disable sending Siri and Dictation information to Apple"
discussion: |
  The ability to submit diagnostic data to Apple must be disabled.
check: |
  /usr/bin/profiles -P -o stdout | /usr/bin/grep -c '"Siri Data Sharing Opt-In Status" = 2;'
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  800-53r4: 
    - CM-7(b)
    - SC-7(10)
    - SI-4
 
macOS:
  - "10.15"
tags:
  - cnssi-1253
  - fisma-low
  - fisma-moderate
  - fisma-high
mobileconfig: true
mobileconfig_info:
  com.apple.assistant.support:
      "Siri Data Sharing Opt-In Status": 2
```
