### ISSUE TITLE
add (sub)subtitles for the documentation.

### ISSUE THREAD

**Issue by mvdbent** [usnistgov/macos_security#59]
### Feature Proposal

add a deeper layer for the documentation in the baselin.yaml

### Feature details

Add to the baseline.yaml for a deeper layer that will result in a 5.1.1 index? 

**Example:**
```
- section: "authentication"
    rules:
      - auth_pam_login_smartcard_enforce
      - subsection: "deeper level authentication"
          subrules:
          - auth_smartcard_allow
  - section: "auditing"
    rules:
      - audit_folder_group_configure
      - audit_failure_halt
```

**Result will be**
```
5. Authentication
5.1. Enforce Multifactor Authentication for Login
5.1.1 Allow Smartcard Authentication
6. Auditing
6.1. Configure Audit Log Folders Group to Wheel
6.2. Configure System to Shut Down Upon Audit Failure

```
